import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * The sidebar is generated from the docs folder structure. Guides are authored
 * by hand, while everything under `docs/extensions` is produced by
 * `npm run generate-docs` in the `tools` package.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
